---
permalink: migrate/migrate-to-latest-ontaptools.html 
sidebar: sidebar 
keywords: migrate 
summary: Bei der Migration von Storage-Daten werden Storage-Back-Ends manuell über REST-APIs integriert. Bei der Migration von VASA Provider-Daten werden die Daten aus der bestehenden Derby-Datenbank exportiert und in die MongoDB-Datenbank importiert. 
---
= Migrieren Sie von ONTAP-Tools für VMware vSphere 9.xx zu 10.3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Verschieben der NetApp ONTAP-Tools für das VMware vSphere-Setup von Version 9.xx auf 10.x erfordert aufgrund der erheblichen Produktaktualisierungen und -verbesserungen in den Versionen einen Migrationsprozess.

Sie können von den ONTAP-Tools für VMware vSphere 9.12D1 und 9.13D2-Versionen auf 10.3 migrieren.

Wenn Ihr Setup NFS- und VMFS-Datenspeicher, aber keine vVols-Datenspeicher enthält, deinstallieren Sie einfach ONTAP Tools 9.xx und installieren Sie ONTAP Tools 10.x. Enthält Ihr Setup jedoch vVols-Datenspeicher, müssen Sie den VASA-Provider und den SRA migrieren.

Die folgende Tabelle skizziert den Migrationsprozess in diesen beiden unterschiedlichen Szenarien.

|===
| *Wenn das Setup über vVols-Datenspeicher verfügt* | *Wenn das Setup nur NFS- und VMFS-Datenspeicher enthält* 


| Schritte: 1. link:../migrate/sra-vasa-migration.html["Migrieren des VASA-Anbieters"] 2.  https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html["Erstellen von VM-Speicherrichtlinien"] | Schritte: 1. Entfernen Sie ONTAP Tools 9.xx aus Ihrer Umgebung. Siehe  https://kb.netapp.com/data-mgmt/OTV/VSC_Kbs/OTV_How_to_remove_OTV_9_12_from_your_environment["So entfernen Sie OTV 9.xx aus Ihrer Umgebung"] NetApp Knowledge Base-Artikel. 2. link:../deploy/quick-start.html["Bereitstellen und Konfigurieren von ONTAP-Tools für VMware vSphere 10.3"] 3. link:../migrate/sra-vasa-migration.html["Aktualisieren Sie das SRA"] 4.  https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html["Erstellen von VM-Speicherrichtlinien"] 
|===

NOTE: Nach der Migration von ONTAP Tools für VMware vSphere 9.xx zu 10.3 werden VVols-Datastores mit NVMe/FC-Protokoll nicht mehr in Betrieb, da die ONTAP Tools 10.3 das NVMe-of-Protokoll nur mit VMFS-Datastores unterstützt.
