---
permalink: protect/map-folder.html 
sidebar: sidebar 
keywords:  
summary: Sie sollten Ihre Ordner auf dem geschützten Standort und dem Wiederherstellungsstandort zuordnen, um die Kommunikation zwischen ihnen zu ermöglichen. 
---
= Konfigurieren von Ordnerzuordnungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten Ihre Ordner auf dem geschützten Standort und dem Wiederherstellungsstandort zuordnen, um die Kommunikation zwischen ihnen zu ermöglichen.

.Bevor Sie beginnen
Sie sollten die geschützten und Recovery-Standorte verbunden haben.

.Schritte
. Melden Sie sich bei vCenter Server an und wählen Sie *Site Recovery* > *Sites*.
. Wählen Sie Ihre geschützte Site aus und wählen Sie *Verwalten*.
. Wählen Sie auf der Registerkarte Verwalten das Symbol *Ordnerzuordnungen* > *Ordner*, um eine neue Ordnerzuordnung zu erstellen.
. Führen Sie im Assistenten zum Erstellen der Ordnerzuordnung folgende Schritte aus:
+
.. Wählen Sie *automatisch Zuordnungen für Ordner mit übereinstimmenden Namen vorbereiten* aus und wählen Sie *Weiter* aus.
.. Wählen Sie die gewünschten Rechenzentrumsobjekte für die geschützten und Recovery-Standorte aus und wählen Sie *Zuordnungen hinzufügen*.
.. Wählen Sie *Weiter*, nachdem Zuordnungen erfolgreich erstellt wurden.
.. Wählen Sie das zuvor verwendete Objekt aus, um eine umgekehrte Zuordnung zu erstellen, und wählen Sie dann *Fertig stellen*.




.Ergebnis
Auf der Seite Ordnerzuordnungen werden die geschützten Site-Ressourcen und die Ressourcen des Recovery-Standorts angezeigt. Sie können die gleichen Schritte für andere Netzwerke in Ihrer Umgebung befolgen.
