---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: Storage-Back-Ends sind Systeme, die die ESXi Hosts zum Speichern von Daten verwenden. 
---
= Fügen Sie ein Storage-Back-End hinzu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch das Hinzufügen eines Storage-Backends können Sie ein ONTAP Cluster integrieren.

*Über diese Aufgabe*

Um einem global gestpleten Cluster in einer mandantenfähigen Architektur ein Storage-Back-End hinzuzufügen, fügen Sie mithilfe des ONTAP Tools Manager das Storage-Back-End hinzu. Nachdem Sie das Storage-Back-End dem globalen Cluster hinzugefügt haben, müssen Sie das Cluster den gewünschten vCenter-Mandanten zuordnen. Der vCenter Mandant muss die gewünschten Storage Virtual Machines (SVMs) integriert haben. Dadurch kann ein SVM-Benutzer VVols Datastore bereitstellen. Sie können Storage in vCenter mithilfe der SVM hinzufügen.

Um einem lokal Scoped-Cluster ein Storage Back-End hinzuzufügen, fügen Sie Ihre ONTAP Systeme direkt über das ONTAP Tools Plug-in auf dem vCenter Server hinzu.

[role="tabbed-block"]
====
.Verwenden des ONTAP Tools Managers
--

NOTE: In einer mandantenfähigen Einrichtung können Sie ein Storage-Back-End-Cluster global und eine lokale SVM hinzufügen, um die SVM-Benutzeranmeldedaten zu verwenden.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Melden Sie sich mit den ONTAP Tools für VMware vSphere Administrator-Anmeldeinformationen an, die Sie während der Implementierung angegeben haben.
. Wählen Sie in der Seitenleiste *Speicher-Backends* aus.
. Fügen Sie das Speicher-Back-End hinzu und geben Sie die IP-Adresse oder den FQDN, den Benutzernamen und das Kennwort des Servers an.
+

NOTE: IPv4- und IPv6-Adressenmanagement-LIFs werden unterstützt.



--
.Die vSphere-Client-Benutzeroberfläche wird verwendet
--

NOTE: Wenn Sie mithilfe der vSphere Client-Benutzeroberfläche ein Storage-Back-End hinzufügen, unterstützt der VVols-Datastore das direkte Hinzufügen eines SVM-Benutzers nicht.

. Melden Sie sich beim vSphere-Client an
. Wählen Sie auf der Shortcuts-Seite unter dem Plug-ins-Abschnitt *NetApp ONTAP Tools* aus.
. Wählen Sie in der Seitenleiste *Speicher-Backends* aus.
. Fügen Sie das Speicher-Back-End hinzu, und geben Sie die IP-Adresse, den Benutzernamen, das Kennwort und die Portdetails des Servers an.
+

NOTE: Zum direkten Hinzufügen eines SVM-Benutzers können Cluster-basierte Anmeldedaten und logische Schnittstellen für das IPv4- und IPv6-Adressmanagement hinzugefügt oder SVM-basierte Anmeldedaten mit einer SVM-Management-LIF bereitgestellt werden.



.Was kommt als Nächstes?
Die Liste wird aktualisiert, und das neu hinzugefügte Storage-Back-End wird in der Liste angezeigt.

--
====