---
permalink: configure/configure-network-access.html 
sidebar: sidebar 
keywords: network access configuration, export policy, mount operation, ESXi hosts 
summary: Wenn Sie den Netzwerkzugriff noch nicht konfiguriert haben, werden standardmäßig alle vom ESXi-Host ermittelten IP-Adressen zur Exportrichtlinie hinzugefügt. 
---
= Konfigurieren Sie den Netzwerkzugriff
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie den Netzwerkzugriff nicht konfiguriert haben, werden standardmäßig alle vom ESXi-Host ermittelten IP-Adressen zur Exportrichtlinie hinzugefügt. Sie können ihn so konfigurieren, dass der Exportrichtlinie einige spezifische IP-Adressen hinzugefügt und der Rest ausgeschlossen wird. Wenn Sie jedoch einen Mount-Vorgang auf den ausgeschlossenen ESXi-Hosts durchführen, schlägt der Vorgang fehl.

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Wählen Sie *NetApp ONTAP Tools* auf der Shortcuts-Seite unter dem Plug-ins-Bereich.
. Navigieren Sie im linken Bereich der ONTAP-Tools zu *Einstellungen* > *Netzwerkzugang verwalten* > *Bearbeiten*.
+
Um mehrere IP-Adressen hinzuzufügen, trennen Sie die Liste durch Kommas, Bereich, klassenloses Inter-Domain Routing (CIDR) oder eine Kombination aller drei.

. Wählen Sie *Speichern*.

