---
permalink: configure/create-datastore.html 
sidebar: sidebar 
keywords:  
summary: Wenn Sie einen Datastore auf Host-Cluster-Ebene erstellen, wird der Datastore auf allen Hosts des Ziels erstellt und gemountet. Die Aktion wird nur aktiviert, wenn der aktuelle Benutzer über die Berechtigung zur Ausführung verfügt. 
---
= Erstellen eines Datenspeichers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie einen Datastore auf Host-Cluster-Ebene erstellen, wird der Datastore auf allen Hosts des Ziels erstellt und gemountet. Die Aktion wird nur aktiviert, wenn der aktuelle Benutzer über die Berechtigung zur Ausführung verfügt.

[role="tabbed-block"]
====
.Erstellen Sie einen VVols-Datastore
--
Ab der Nutzung von ONTAP Tools für VMware vSphere 10.3 können Sie auf ASA r2 Systemen mit Platzeffizienz wie Thin.vVol einen VVols Datastore erstellen. Der VASA Provider erstellt bei der Erstellung des vVol Datastore einen Container und die gewünschten Protokollendpunkte. Dieser Container verfügt nicht über Sicherungsvolumes.

.Bevor Sie beginnen
* Vergewissern Sie sich, dass Root-Aggregate nicht der SVM zugeordnet sind.
* Stellen Sie sicher, dass der VASA Provider beim ausgewählten vCenter registriert ist.
* Im ASA r2 Storage-System sollte die SVM dem Aggregat für SVM-Benutzer zugeordnet werden.


.Schritte
. Melden Sie sich beim vSphere-Client an.
. Klicken Sie mit der rechten Maustaste auf ein Hostsystem, einen Hostcluster oder ein Rechenzentrum, und wählen Sie *NetApp ONTAP Tools* > *Datastore erstellen* aus.
. Wählen Sie VVols *Datenspeichertyp* aus.
. Geben Sie die Informationen *Datastore Name* und *Protocol* ein.
+

NOTE: Das ASA r2 System unterstützt die iSCSI- und FC-Protokolle für VVols.

. Wählen Sie die Storage-VM aus, auf der der Datastore erstellt werden soll.
. Wählen Sie in den *Erweiterten Optionen* eine benutzerdefinierte Exportrichtlinie für das NFS-Protokoll oder einen benutzerdefinierten Initiatorgruppennamen für die iSCSI- und FC-Protokolle aus.
+

NOTE: Beim Typ SVM des ASA r2 Storage-Systems werden Storage-Einheiten (LUN/Namespace) nicht erstellt, da der Datastore nur ein logischer Container ist.

. Im Bereich *Speicherattribute* können Sie neue Volumes erstellen oder die vorhandenen Volumes verwenden. Sie können diese beiden Volume-Typen jedoch nicht kombinieren, um einen VVols-Datastore zu erstellen.
+
Beim Erstellen eines neuen Volumes können Sie die QoS auf dem Datastore aktivieren. Standardmäßig wird für jede Anforderung, die eine LUN erstellt hat, ein Volume erstellt. Dieser Schritt gilt nicht für VVols-Datastores, die ASA r2 Storage-Systeme verwenden.

. Überprüfen Sie Ihre Auswahl im Fenster *Zusammenfassung* und wählen Sie *Fertig stellen*.


--
.Erstellen Sie einen NFS-Datastore
--
Ein Datastore des VMware Network File System (NFS) verwendet das NFS-Protokoll, um ESXi-Hosts über ein Netzwerk mit einem Shared Storage-Gerät zu verbinden. NFS-Datastores werden häufig in VMware vSphere Umgebungen verwendet und bieten verschiedene Vorteile, z. B. Einfachheit und Flexibilität.

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Klicken Sie mit der rechten Maustaste auf ein Hostsystem, einen Hostcluster oder ein Rechenzentrum, und wählen Sie *NetApp ONTAP Tools* > *Datastore erstellen* aus.
. Wählen Sie NFS im Feld *Datastore type* aus.
. Geben Sie den Namen, die Größe und die Protokollinformationen des Datastore im Bereich *Name und Protokoll* ein. Wählen Sie in den erweiterten Optionen *Datastore Cluster* und *Kerberos-Authentifizierung* aus.
+

NOTE: Kerberos-Authentifizierung ist nur verfügbar, wenn das NFS 4.1-Protokoll ausgewählt ist.

. Wählen Sie *Plattform* und *Storage VM* im Bereich *Storage* aus.
. Wählen Sie *Custom Export Policy* unter Advanced options, falls erforderlich, aber es wird nicht empfohlen. Falls verwendet, stellen Sie sicher, dass Sie die Erkennung in vCenter für alle Objekte ausführen.
+

NOTE: Sie können keinen NFS-Datastore mit der Standard-/Root-Volume-Richtlinie der SVM erstellen.

+
** In den erweiterten Optionen ist die Umschalttaste *Asymmetric* nur sichtbar, wenn Leistung oder Kapazität in der Dropdown-Liste Plattform ausgewählt ist.
** Wenn Sie die Option *any* in der Dropdown-Liste der Plattform wählen, sehen Sie die SVMs, die Teil des vCenter sind, unabhängig von der Plattform oder dem asymmetrischen Flag.


. Wählen Sie im Bereich *Speicherattribute* das Aggregat für die Volume-Erstellung aus. Wählen Sie in den erweiterten Optionen je nach Bedarf *Space Reserve* und *Enable QoS* aus.
. Überprüfen Sie die Auswahl im Fenster *Zusammenfassung* und wählen Sie *Fertig stellen*.


Der NFS Datastore wird auf allen Hosts erstellt und gemountet.

--
.Erstellen Sie einen VMFS-Datastore
--
Virtual Machine File System (VMFS) ist ein geclustertes Dateisystem, das Dateien von virtuellen Maschinen in VMware vSphere Umgebungen speichert. Mit VMFS können mehrere ESXi-Hosts gleichzeitig auf dieselben VM-Dateien zugreifen, wodurch Funktionen wie vMotion und Hochverfügbarkeit aktiviert werden.

In einem geschützten Cluster:

* Sie können nur VMFS-Datastores erstellen. Wenn Sie einem geschützten Cluster einen VMFS Datastore hinzufügen, wird dieser automatisch gesichert.
* Sie können keinen Datastore in einem Rechenzentrum mit einem oder mehreren geschützten Host-Clustern erstellen.
* Sie können keinen Datastore auf dem ESXi-Host erstellen, wenn der übergeordnete Host-Cluster durch eine Beziehung des Typs „automatisierte Failover-Duplex-Richtlinie“ geschützt ist (einheitliche/uneinheitliche Konfiguration).
* Sie können einen VMFS-Datastore nur auf einem ESXi-Host erstellen, der durch eine asynchrone Beziehung geschützt ist. Sie können keinen Datastore auf einem ESXi-Host erstellen und mounten, der Teil eines Host-Clusters ist, der durch die Richtlinie „Automatischer Failover-Duplex“ geschützt ist.


.Bevor Sie beginnen
* Aktivieren Sie Services und LIFs für jedes Protokoll auf der ONTAP Storage-Seite.
* SVM-Aggregat für SVM-Benutzer im ASA r2 Storage-System zuordnen
* Konfigurieren Sie den ESXi-Host, wenn Sie das NVMe/TCP-Protokoll verwenden:
+
.. Überprüfen Sie die https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=san&productid=49677&releases_filter=589,578,518,508,448&deviceCategory=san&details=1&partner=399&Protocols=1&transportTypes=3&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["VMware Compatibility Guide"]
+

NOTE: VMware vSphere 7.0 U3 und höher unterstützen das NVMe/TCP-Protokoll. Es wird jedoch VMware vSphere 8.0 und eine neuere Version empfohlen.

.. Überprüfen Sie, ob der NIC-Anbieter (Network Interface Card) ESXi NIC mit NVMe/TCP-Protokoll unterstützt.
.. Konfigurieren Sie die ESXi-NIC für NVMe/TCP gemäß den Spezifikationen des NIC-Anbieters.
.. Wenn Sie VMware vSphere 7-Version verwenden, befolgen Sie die Anweisungen auf der VMware-Site https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/configure-adapters-for-nvme-over-tcp-storage/configure-vmkernel-binding-for-the-tcp-adapter.html["Konfigurieren Sie die VMkernel Bindung für den NVMe over TCP Adapter"], um die NVMe/TCP-Portbindung zu konfigurieren. Wenn Sie VMware vSphere 8 Version verwenden, folgen Sie https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-tcp-on-esxi.html["Konfiguration von NVMe over TCP auf ESXi"], um die NVMe/TCP-Portbindung zu konfigurieren.
.. Folgen Sie für VMware vSphere 7 Release den Anweisungen auf Seite https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["Aktivieren Sie NVMe over RDMA oder NVMe over TCP-Softwareadapter"], um NVMe/TCP-Softwareadapter zu konfigurieren. Folgen Sie bei VMware vSphere 8 Version, https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-rdma-roce-v2-on-esxi/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["Fügen Sie Software-NVMe-over-RDMA- oder NVMe-over-TCP-Adapter hinzu"] um die NVMe/TCP-Softwareadapter zu konfigurieren.
.. Führen Sie link:../configure/discover-storage-systems-and-hosts.html["Erkennen von Storage-Systemen und Hosts"]eine Aktion auf dem ESXi-Host aus. Weitere Informationen finden Sie unter https://community.netapp.com/t5/Tech-ONTAP-Blogs/How-to-Configure-NVMe-TCP-with-vSphere-8-0-Update-1-and-ONTAP-9-13-1-for-VMFS/ba-p/445429["Konfigurieren von NVMe/TCP mit vSphere 8.0 Update 1 und ONTAP 9.13.1 für VMFS-Datenspeicher"].


* Wenn Sie das NVME/FC-Protokoll verwenden, führen Sie die folgenden Schritte aus, um den ESXi-Host zu konfigurieren:
+
.. Aktivieren Sie NVMe over Fabrics (NVMe-of) auf Ihren ESXi Hosts.
.. Vollständiges SCSI-Zoning
.. Stellen Sie sicher, dass ESXi-Hosts und das ONTAP-System auf einer physischen und einer logischen Ebene verbunden sind.




Informationen zum Konfigurieren einer ONTAP SVM für das FC-Protokoll finden Sie unter https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-fc-task.html["Konfigurieren Sie eine SVM für FC"].

Weitere Informationen zur Nutzung des NVMe/FC-Protokolls mit VMware vSphere 8.0 finden Sie unter https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["NVMe-of Host-Konfiguration für ESXi 8.x mit ONTAP"].

Weitere Informationen zur Verwendung von NVMe/FC mit VMware vSphere 7.0 finden Sie unter https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["ONTAP NVMe/FC-Host-Konfigurationsleitfaden"] und http://www.netapp.com/us/media/tr-4684.pdf["TR-4684"].

.Schritte
. Melden Sie sich beim vSphere-Client an.
. Klicken Sie mit der rechten Maustaste auf ein Hostsystem, einen Hostcluster oder ein Rechenzentrum, und wählen Sie *NetApp ONTAP Tools* > *Datastore erstellen* aus.
. Wählen Sie den VMFS-Datastore-Typ aus.
. Geben Sie den Namen, die Größe und die Protokollinformationen des Datastore im Bereich *Name und Protokoll* ein. Wenn Sie den neuen Datastore zu einem vorhandenen VMFS Datastore-Cluster hinzufügen möchten, wählen Sie unter Erweiterte Optionen die Datastore-Cluster-Auswahl aus.
. Wählen Sie Speicher-VM im Bereich *Speicher* aus. Geben Sie den *Custom Initiator Group Name* im Abschnitt *Advanced options* nach Bedarf an. Sie können eine vorhandene Initiatorgruppe für den Datastore auswählen oder eine neue Initiatorgruppe mit einem benutzerdefinierten Namen erstellen.
+
Bei Auswahl des NVMe/FC- oder NVMe/TCP-Protokolls wird ein neues Namespace-Subsystem erstellt und für die Namespace-Zuordnung verwendet. Das Namespace-Subsystem wird mit dem automatisch generierten Namen erstellt, der den Datastore-Namen enthält. Sie können das Namespace-Subsystem im Feld *Custom Namespace Subsystem Name* in den erweiterten Optionen des Fensters *Storage* umbenennen.

. Im Bereich *Storage attributes*:
+
.. Wählen Sie aus den Dropdown-Optionen *Aggregate* aus.
+

NOTE: Bei ASA r2-Speichersystemen wird die Option *Aggregate* nicht angezeigt, da es sich bei ASA r2-Speicher um einen disaggregierten Speicher handelt. Wenn Sie eine ASA r2 Storage-System-Typ SVM auswählen, werden auf der Seite Storage-Attribute die Optionen zur Aktivierung der QoS angezeigt.

.. Nach dem ausgewählten Protokoll wird eine Storage-Einheit (LUN/Namespace) mit einer Platzreserve des Typs Thin erstellt.
.. Wählen Sie *vorhandenes Volume verwenden*, *QoS*-Optionen nach Bedarf aktivieren und geben Sie die Details an.
+

NOTE: Im ASA r2-Speichertyp ist die Volume-Erstellung oder -Auswahl für die Erstellung von Speichereinheiten (LUN/Namespace) nicht anwendbar. Daher werden diese Optionen nicht angezeigt.

+

NOTE: Bei der Erstellung eines VMFS-Datastore mit einem NVMe/FC- oder NVMe/TCP-Protokoll können Sie das vorhandene Volume nicht verwenden, sondern müssen ein neues Volume erstellen.



. Überprüfen Sie die Datastore-Details im Bereich *Summary* und wählen Sie *Finish*.



NOTE: Wenn Sie den Datastore auf einem geschützten Cluster erstellen, wird eine schreibgeschützte Meldung angezeigt: „Der Datastore wird auf einem geschützten Cluster gemountet.“

.Ergebnis
Der VMFS Datastore wird auf allen Hosts erstellt und gemountet.

--
====