---
permalink: manage/edit-esxi-host-settings.html 
sidebar: sidebar 
keywords:  
summary: Über das Dashboard der ONTAP Tools für VMware vSphere können Sie Ihre ESXi Host-Einstellungen bearbeiten. 
---
= Ändern Sie ESXi Hosteinstellungen mithilfe von ONTAP Tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Über das Dashboard der ONTAP Tools für VMware vSphere können Sie Ihre ESXi Host-Einstellungen bearbeiten.

.Bevor Sie beginnen
Wenn ein Problem mit den ESXi-Hosteinstellungen auftritt, wird das Problem im Portlet „ESXi-Hostsysteme“ des Dashboards angezeigt. Sie können das Problem auswählen, um den Hostnamen oder die IP-Adresse des ESXi-Hosts anzuzeigen, auf dem das Problem aufgetreten ist.

.Schritte
. Melden Sie sich beim vSphere-Client an
. Wählen Sie auf der Shortcuts-Seite unter dem Plug-ins-Abschnitt *NetApp ONTAP Tools* aus.
. Gehen Sie in der Übersicht (Dashboard) des ONTAP Tools for VMware vSphere Plug-ins zum Portlet *ESXi Host Compliance*.
. Wählen Sie den Link *Empfohlene Einstellungen anwenden*.
. Wählen Sie im Fenster *empfohlene Hosteinstellungen anwenden* die Hosts aus, die Sie den von NetApp empfohlenen Hosteinstellungen entsprechen möchten, und wählen Sie *Weiter* aus.
+

NOTE: Sie können den ESXi-Host erweitern, um die aktuellen Werte anzuzeigen.

. Wählen Sie auf der Einstellungsseite die empfohlenen Werte nach Bedarf aus.
. Überprüfen Sie im Übersichtsfenster die Werte und wählen Sie *Fertig stellen*. Sie können den Fortschritt im Fenster „Letzte Aufgabe“ verfolgen.


*Verwandte Informationen*

link:../configure/configure-esx-server-multipath-and-timeout-settings.html["Konfigurieren Sie ESXi-Hosteinstellungen"]
