---
permalink: manage/expand-storage-of-vvol-datastore.html 
sidebar: sidebar 
keywords: virtual volume datastores 
summary: Wenn Sie in der vCenter-Objektansicht mit der rechten Maustaste auf das Datastore-Objekt klicken, werden im Abschnitt Plug-in ONTAP-Tools für von VMware vSphere unterstützte Aktionen angezeigt. 
---
= Erweitern Sie den VVols Datastore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie in der vCenter-Objektansicht mit der rechten Maustaste auf das Datastore-Objekt klicken, werden im Abschnitt Plug-in ONTAP-Tools für von VMware vSphere unterstützte Aktionen angezeigt. Bestimmte Aktionen werden abhängig vom Typ des Datenspeichers und den aktuellen Benutzerberechtigungen aktiviert.


NOTE: Das erweitern des VVols-Datastore ist für ASA r2-basierten VVols-Datastore nicht möglich.

.Schritte
. Wählen Sie auf der vSphere Client-Startseite *Hosts und Cluster* aus.
. Wählen Sie im Navigationsbereich das Rechenzentrum aus, das den Datastore enthält.
. Klicken Sie mit der rechten Maustaste auf den Datastore und wählen Sie *NetApp ONTAP Tools* > *Speicher zum Datastore hinzufügen*.
. Im Fenster *create oder Select Volumes* können Sie entweder neue Volumes erstellen oder aus den vorhandenen Volumes auswählen. Die Benutzeroberfläche ist selbsterklärend. Befolgen Sie die Anweisungen gemäß Ihrer Wahl.
. Überprüfen Sie im Fenster *Summary* die Auswahl und wählen Sie *Expand*. Sie können den Fortschritt im Fenster „Letzte Aufgaben“ verfolgen.

