---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords:  
summary: Wenn Sie das Passwort für den ONTAP Tools Manager vergessen haben, können Sie die Administratoranmeldedaten mithilfe des Tokens zurücksetzen, das von den ONTAP Tools für die VMware vSphere-Wartungskonsole generiert wurde. 
---
= Kennwort des ONTAP Tools Managers zurücksetzen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Falls Sie das Passwort des ONTAP Tools Managers vergessen haben, können Sie die Administratoranmeldedaten mithilfe des Tokens zurücksetzen, das von den ONTAP Tools für die VMware vSphere Wartungskonsole generiert wurde.

.Schritte
. Starten Sie den ONTAP Tools Manager über einen Webbrowser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Wählen Sie auf dem Anmeldebildschirm die Option *Passwort zurücksetzen*.
+
Zum Zurücksetzen des Manager-Passworts müssen Sie das Reset-Token mithilfe der ONTAP-Tools für die VMware vSphere-Wartungskonsole generieren.

+
.. Öffnen Sie vom vCenter Server aus die Wartungskonsole
.. Geben Sie „2“ ein, um die Option „Systemkonfiguration“ auszuwählen
.. Geben Sie '3' ein, um das 'Wartungs'-Benutzerpasswort zu ändern.


. Geben Sie im Popup-Fenster Passwort ändern den Token zum Zurücksetzen des Passworts, den Benutzernamen und die neuen Kennwortdetails ein.
. Wählen Sie *Reset*, um die Änderungen umzusetzen. Nach erfolgreichem Zurücksetzen des Passworts können Sie sich mit dem neuen Passwort anmelden.

